name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Upload Release to GitHub & Wally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}
      - name: Build project
        run: |
          rm -rf .foreman-install
          wally package --output Option.zip
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Publish release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          fail_on_unmatched_files: true
          files: |
            Option.zip
      - name: Publish release to Wally
        shell: bash
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish --verbose
